services:
  runner:
    image: ghrunner
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 4
