services:
  runner:
    image: vsbmeza/github-runner-linux:latest
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      REPO: '<owner>/<repo>'
      TOKEN: '<your-personal-access-token>'
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 128M
